"""
Catálogo de Defensorías Públicas, Defensorías del Pueblo y Ombudspersons
de Derechos Humanos en las Américas.
"""

INSTITUCIONES = [
    # ─── SUDAMÉRICA ────────────────────────────────────────────────────────────
    {
        "pais": "Argentina",
        "region": "Sudamérica",
        "nombre": "Defensoría General de la Nación",
        "tipo": "Defensoria Pública",
        "url": "https://www.mpd.gov.ar",
        "idioma": "es",
    },
    {
        "pais": "Argentina",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo de la Nación",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoriadelpueblo.gov.ar",
        "idioma": "es",
    },
    {
        "pais": "Bolivia",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo de Bolivia",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoria.gob.bo",
        "idioma": "es",
    },
    {
        "pais": "Brasil",
        "region": "Sudamérica",
        "nombre": "Defensoria Pública da União",
        "tipo": "Defensoria Pública",
        "url": "https://www.dpu.def.br",
        "idioma": "pt",
    },
    {
        "pais": "Brasil",
        "region": "Sudamérica",
        "nombre": "Defensoria Pública do Estado de São Paulo",
        "tipo": "Defensoria Pública",
        "url": "https://www.defensoria.sp.def.br",
        "idioma": "pt",
    },
    {
        "pais": "Brasil",
        "region": "Sudamérica",
        "nombre": "Defensoria Pública do Estado do Rio de Janeiro",
        "tipo": "Defensoria Pública",
        "url": "https://defensoria.rj.def.br",
        "idioma": "pt",
    },
    {
        "pais": "Brasil",
        "region": "Sudamérica",
        "nombre": "Defensoria Pública do Estado de Pernambuco",
        "tipo": "Defensoria Pública",
        "url": "https://www.defensoria.pe.def.br",
        "idioma": "pt",
    },
    {
        "pais": "Chile",
        "region": "Sudamérica",
        "nombre": "Defensoría Penal Pública",
        "tipo": "Defensoria Pública",
        "url": "https://www.dpp.cl",
        "idioma": "es",
    },
    {
        "pais": "Chile",
        "region": "Sudamérica",
        "nombre": "Defensoría de la Niñez",
        "tipo": "Ombudsperson",
        "url": "https://www.defensorianinez.cl",
        "idioma": "es",
    },
    {
        "pais": "Chile",
        "region": "Sudamérica",
        "nombre": "Instituto Nacional de Derechos Humanos (INDH)",
        "tipo": "Ombudsperson",
        "url": "https://www.indh.cl",
        "idioma": "es",
    },
    {
        "pais": "Colombia",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo de Colombia",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoria.gov.co",
        "idioma": "es",
    },
    {
        "pais": "Ecuador",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo del Ecuador",
        "tipo": "Ombudsperson",
        "url": "https://www.dpe.gob.ec",
        "idioma": "es",
    },
    {
        "pais": "Guyana",
        "region": "Sudamérica",
        "nombre": "Office of the Ombudsman of Guyana",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.gov.gy",
        "idioma": "en",
    },
    {
        "pais": "Paraguay",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo del Paraguay",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoria.gov.py",
        "idioma": "es",
    },
    {
        "pais": "Perú",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo del Perú",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoria.gob.pe",
        "idioma": "es",
    },
    {
        "pais": "Suriname",
        "region": "Sudamérica",
        "nombre": "Bureau Nationale Ombudsman Suriname",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.sr",
        "idioma": "nl",
    },
    {
        "pais": "Uruguay",
        "region": "Sudamérica",
        "nombre": "Institución Nacional de Derechos Humanos y Defensoría del Pueblo",
        "tipo": "Ombudsperson",
        "url": "https://www.inddhh.gub.uy",
        "idioma": "es",
    },
    {
        "pais": "Venezuela",
        "region": "Sudamérica",
        "nombre": "Defensoría del Pueblo de Venezuela",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoria.gob.ve",
        "idioma": "es",
    },
    # ─── CENTROAMÉRICA ─────────────────────────────────────────────────────────
    {
        "pais": "Belice",
        "region": "Centroamérica",
        "nombre": "Office of the Ombudsman of Belize",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.gov.bz",
        "idioma": "en",
    },
    {
        "pais": "Costa Rica",
        "region": "Centroamérica",
        "nombre": "Defensoría de los Habitantes de Costa Rica",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoriadh.go.cr",
        "idioma": "es",
    },
    {
        "pais": "El Salvador",
        "region": "Centroamérica",
        "nombre": "Procuraduría para la Defensa de los Derechos Humanos",
        "tipo": "Ombudsperson",
        "url": "https://www.pddh.gob.sv",
        "idioma": "es",
    },
    {
        "pais": "Guatemala",
        "region": "Centroamérica",
        "nombre": "Procuraduría de los Derechos Humanos de Guatemala",
        "tipo": "Ombudsperson",
        "url": "https://www.pdh.org.gt",
        "idioma": "es",
    },
    {
        "pais": "Honduras",
        "region": "Centroamérica",
        "nombre": "Comisionado Nacional de los Derechos Humanos (CONADEH)",
        "tipo": "Ombudsperson",
        "url": "https://www.conadeh.hn",
        "idioma": "es",
    },
    {
        "pais": "México",
        "region": "Centroamérica",
        "nombre": "Comisión Nacional de los Derechos Humanos (CNDH)",
        "tipo": "Ombudsperson",
        "url": "https://www.cndh.org.mx",
        "idioma": "es",
    },
    {
        "pais": "México",
        "region": "Centroamérica",
        "nombre": "Instituto Federal de Defensoría Pública",
        "tipo": "Defensoria Pública",
        "url": "https://www.ifdp.cjf.gob.mx",
        "idioma": "es",
    },
    {
        "pais": "Nicaragua",
        "region": "Centroamérica",
        "nombre": "Procuraduría para la Defensa de los Derechos Humanos de Nicaragua",
        "tipo": "Ombudsperson",
        "url": "https://www.pddh.gob.ni",
        "idioma": "es",
    },
    {
        "pais": "Panamá",
        "region": "Centroamérica",
        "nombre": "Defensoría del Pueblo de Panamá",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoriadelpueblo.gob.pa",
        "idioma": "es",
    },
    # ─── CARIBE ────────────────────────────────────────────────────────────────
    {
        "pais": "Barbados",
        "region": "Caribe",
        "nombre": "Office of the Ombudsman of Barbados",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.gov.bb",
        "idioma": "en",
    },
    {
        "pais": "Cuba",
        "region": "Caribe",
        "nombre": "Fiscalía General de la República de Cuba",
        "tipo": "Defensoria Pública",
        "url": "https://www.fiscalia.gob.cu",
        "idioma": "es",
    },
    {
        "pais": "Haití",
        "region": "Caribe",
        "nombre": "Office de la Protection du Citoyen (OPC)",
        "tipo": "Ombudsperson",
        "url": "https://www.opc.gouv.ht",
        "idioma": "fr",
    },
    {
        "pais": "Jamaica",
        "region": "Caribe",
        "nombre": "Office of the Public Defender of Jamaica",
        "tipo": "Ombudsperson",
        "url": "https://www.opd.gov.jm",
        "idioma": "en",
    },
    {
        "pais": "República Dominicana",
        "region": "Caribe",
        "nombre": "Defensoría del Pueblo de la República Dominicana",
        "tipo": "Ombudsperson",
        "url": "https://www.defensoriadelpueblo.gob.do",
        "idioma": "es",
    },
    {
        "pais": "Trinidad y Tobago",
        "region": "Caribe",
        "nombre": "Office of the Ombudsman of Trinidad and Tobago",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.gov.tt",
        "idioma": "en",
    },
    # ─── NORTEAMÉRICA ──────────────────────────────────────────────────────────
    {
        "pais": "Canadá",
        "region": "Norteamérica",
        "nombre": "Office of the Ombudsman for National Defence and Canadian Forces",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.forces.gc.ca",
        "idioma": "en",
    },
    {
        "pais": "Canadá",
        "region": "Norteamérica",
        "nombre": "Office of the Federal Ombudsman for Victims of Crime",
        "tipo": "Ombudsperson",
        "url": "https://www.victimsfirst.gc.ca",
        "idioma": "en",
    },
    {
        "pais": "Canadá",
        "region": "Norteamérica",
        "nombre": "Ontario Ombudsman",
        "tipo": "Ombudsperson",
        "url": "https://www.ombudsman.on.ca",
        "idioma": "en",
    },
    {
        "pais": "Canadá",
        "region": "Norteamérica",
        "nombre": "Protecteur du citoyen du Québec",
        "tipo": "Ombudsperson",
        "url": "https://www.protecteurducitoyen.qc.ca",
        "idioma": "fr",
    },
    {
        "pais": "Estados Unidos",
        "region": "Norteamérica",
        "nombre": "National Association for Public Defense (NAPD)",
        "tipo": "Defensoria Pública",
        "url": "https://www.publicdefenders.us",
        "idioma": "en",
    },
    {
        "pais": "Estados Unidos",
        "region": "Norteamérica",
        "nombre": "Federal Public Defender - Southern District of California",
        "tipo": "Defensoria Pública",
        "url": "https://www.fd.org",
        "idioma": "en",
    },
    # ─── ORGANISMOS REGIONALES ─────────────────────────────────────────────────
    {
        "pais": "Regional",
        "region": "Américas",
        "nombre": "Asociación Interamericana de Defensorías Públicas (AIDEF)",
        "tipo": "Red Regional",
        "url": "https://www.aidef.org",
        "idioma": "es",
    },
    {
        "pais": "Regional",
        "region": "Américas",
        "nombre": "Instituto Latinoamericano del Ombudsman - Defensor del Pueblo (ILO)",
        "tipo": "Red Regional",
        "url": "https://www.iloombudsman.org",
        "idioma": "es",
    },
    {
        "pais": "Regional",
        "region": "Américas",
        "nombre": "Federación Iberoamericana del Ombudsman (FIO)",
        "tipo": "Red Regional",
        "url": "https://www.portalfio.org",
        "idioma": "es",
    },
    {
        "pais": "Regional",
        "region": "Américas",
        "nombre": "CIDH - Comisión Interamericana de Derechos Humanos",
        "tipo": "Organismo Internacional",
        "url": "https://www.oas.org/es/cidh",
        "idioma": "es",
    },
]
